trigger:
- main

pool: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@15
    npm install
    ng build --configuration=production
  displayName: 'npm install and build'

# Configurar AWS CLI con las credenciales de la Service Connection
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'aws-connection'
    regionName: 'us-east-2'
    inlineScript: |
      aws s3 sync dist/ s3://app-fronted-aws --delete
      aws cloudfront create-invalidation --distribution-id E1TNJZT63JZO07 --paths "/*"
  displayName: 'Deploy to S3 and Invalidate CloudFront'
