trigger:
- main

pool: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli@15 @aws-amplify/cli
  displayName: 'Install Angular & Amplify CLI'

- script: |
    npm install
  displayName: 'Install project dependencies'

- script: |
    amplify pull --appId dzhmw133lv1v1 --envName dev --yes
  displayName: 'Pull AWS Amplify environment'

- script: |
    ng build --configuration=production
  displayName: 'Build Angular project'

- script: ls -la dist/
  displayName: 'List contents of dist/'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'aws-connection'
    regionName: 'us-east-2'
    awsCommand: 's3'
    awsSubCommand: 'sync'
    awsArguments: 'dist/frontend-aws s3://app-fronted-aws --delete'
  displayName: 'Upload to S3'

- task: AWSCLI@1
  inputs:
    awsCredentials: 'aws-connection'
    awsCommand: 'cloudfront'
    awsSubCommand: 'create-invalidation'
    awsArguments: '--distribution-id E1TNJZT63JZO07 --paths "/*"'
  displayName: 'Invalidate CloudFront'

